<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener todas las ciudades para una búsqueda eficiente
        $cities = City::all()->keyBy('name');

        // Definir todos los municipios con su ciudad asociada
        $allMunicipalities = [
            // Amazonas
            ['name' => 'Alto Orinoco', 'city' => 'La Esmeralda'],
            ['name' => 'Atabapo', 'city' => 'San Fernando de Atabapo'],
            ['name' => 'Atures', 'city' => 'Puerto Ayacucho'],
            ['name' => 'Autana', 'city' => 'Isla Ratón'],
            ['name' => 'Manapiare', 'city' => 'San Juan de Manapiare'],
            ['name' => 'Maroa', 'city' => 'Maroa'],
            ['name' => 'Río Negro', 'city' => 'San Carlos de Río Negro'],
            // Anzoátegui
            ['name' => 'Anaco', 'city' => 'Anaco'],
            ['name' => 'Aragua', 'city' => 'Aragua de Barcelona'],
            ['name' => 'Bolívar', 'city' => 'Barcelona'],
            ['name' => 'Bruzual', 'city' => 'Puerto Píritu'],
            ['name' => 'Cajigal', 'city' => 'Onoto'],
            ['name' => 'Carvajal', 'city' => 'Valle de Guanape'],
            ['name' => 'Freites', 'city' => 'Cantaura'],
            ['name' => 'Guanipa', 'city' => 'El Tigrito'],
            ['name' => 'Guanta', 'city' => 'Guanta'],
            ['name' => 'Independencia', 'city' => 'Soledad'],
            ['name' => 'Libertad', 'city' => 'San Mateo'],
            ['name' => 'Machado', 'city' => 'Pariaguán'],
            ['name' => 'Miranda', 'city' => 'El Chaparro'],
            ['name' => 'Monagas', 'city' => 'Mapire'],
            ['name' => 'Peñalver', 'city' => 'Puerto Píritu'],
            ['name' => 'Píritu', 'city' => 'Píritu'],
            ['name' => 'San Juan de Capistrano', 'city' => 'Boca de Uchire'],
            ['name' => 'Santa Ana', 'city' => 'Santa Ana'],
            ['name' => 'Simón Bolívar', 'city' => 'Barcelona'],
            ['name' => 'Simón Rodríguez', 'city' => 'El Tigre'],
            ['name' => 'Sotillo', 'city' => 'Puerto La Cruz'],
            // Apure
            ['name' => 'Achaguas', 'city' => 'Achaguas'],
            ['name' => 'Biruaca', 'city' => 'Biruaca'],
            ['name' => 'Páez', 'city' => 'Guasdualito'],
            ['name' => 'Pedro Camejo', 'city' => 'San Juan de Payara'],
            ['name' => 'Rómulo Gallegos', 'city' => 'Elorza'],
            ['name' => 'San Fernando', 'city' => 'San Fernando de Apure'],
            ['name' => 'Muñoz', 'city' => 'Bruzual'],
            // Aragua
            ['name' => 'Bolívar', 'city' => 'San Mateo'],
            ['name' => 'Cagua', 'city' => 'Cagua'],
            ['name' => 'Camatagua', 'city' => 'Camatagua'],
            ['name' => 'Girardot', 'city' => 'Maracay'],
            ['name' => 'José Ángel Lamas', 'city' => 'Santa Cruz de Aragua'],
            ['name' => 'Libertador', 'city' => 'Palo Negro'],
            ['name' => 'Mariño', 'city' => 'Turmero'],
            ['name' => 'Mario Briceño Iragorry', 'city' => 'El Limón'],
            ['name' => 'José Félix Ribas', 'city' => 'La Victoria'],
            ['name' => 'Revenga', 'city' => 'El Consejo'],
            ['name' => 'San Casimiro', 'city' => 'San Casimiro'],
            ['name' => 'San Sebastián', 'city' => 'San Sebastián de los Reyes'],
            ['name' => 'Sucre', 'city' => 'Cagua'],
            ['name' => 'Tovar', 'city' => 'La Colonia Tovar'],
            ['name' => 'Urdaneta', 'city' => 'Barbacoas'],
            ['name' => 'Zamora', 'city' => 'Villa de Cura'],
            // Barinas
            ['name' => 'Alberto Arvelo Torrealba', 'city' => 'Sabaneta'],
            ['name' => 'Andrés Eloy Blanco', 'city' => 'El Cantón'],
            ['name' => 'Antonio José de Sucre', 'city' => 'Socopó'],
            ['name' => 'Arismendi', 'city' => 'Arismendi'],
            ['name' => 'Barinas', 'city' => 'Barinas'],
            ['name' => 'Bolívar', 'city' => 'Barinitas'],
            ['name' => 'Cruz Paredes', 'city' => 'Barrancas'],
            ['name' => 'Obispos', 'city' => 'Obispos'],
            ['name' => 'Pedraza', 'city' => 'Ciudad Bolivia'],
            ['name' => 'Rojas', 'city' => 'Libertad'],
            ['name' => 'Sosa', 'city' => 'Ciudad de Nutrias'],
            // Bolívar
            ['name' => 'Angostura del Orinoco', 'city' => 'Ciudad Bolívar'],
            ['name' => 'Caroní', 'city' => 'Ciudad Guayana'],
            ['name' => 'Cedeño', 'city' => 'Caicara del Orinoco'],
            ['name' => 'El Callao', 'city' => 'El Callao'],
            ['name' => 'Gran Sabana', 'city' => 'Santa Elena de Uairén'],
            ['name' => 'Piar', 'city' => 'Upata'],
            ['name' => 'Angostura', 'city' => 'Ciudad Piar'],
            ['name' => 'Sifontes', 'city' => 'Tumeremo'],
            ['name' => 'Sucre', 'city' => 'Marhuanta'],
            ['name' => 'Padre Pedro Chien', 'city' => 'El Palmar'],
            // Carabobo
            ['name' => 'Bejuma', 'city' => 'Bejuma'],
            ['name' => 'Carlos Arvelo', 'city' => 'Campo de Carabobo'],
            ['name' => 'Diego Ibarra', 'city' => 'Mariara'],
            ['name' => 'Guacara', 'city' => 'Guacara'],
            ['name' => 'Juan José Mora', 'city' => 'Morón'],
            ['name' => 'Libertador', 'city' => 'Tocuyito'],
            ['name' => 'Los Guayos', 'city' => 'Los Guayos'],
            ['name' => 'Miranda', 'city' => 'Miranda'],
            ['name' => 'Montalbán', 'city' => 'Montalbán'],
            ['name' => 'Naguanagua', 'city' => 'Naguanagua'],
            ['name' => 'Puerto Cabello', 'city' => 'Puerto Cabello'],
            ['name' => 'San Diego', 'city' => 'San Diego'],
            ['name' => 'San Joaquín', 'city' => 'San Joaquín'],
            ['name' => 'Valencia', 'city' => 'Valencia'],
            // Cojedes
            ['name' => 'Anzoátegui', 'city' => 'Cojedes'],
            ['name' => 'Lima Blanco', 'city' => 'Macapo'],
            ['name' => 'Pao de San Juan Bautista', 'city' => 'El Pao'],
            ['name' => 'Ricaurte', 'city' => 'Libertad'],
            ['name' => 'Rómulo Gallegos', 'city' => 'El Baúl'],
            ['name' => 'San Carlos', 'city' => 'San Carlos'],
            ['name' => 'Tinaco', 'city' => 'Tinaco'],
            ['name' => 'Tinaquillo', 'city' => 'Tinaquillo'],
            ['name' => 'Girardot', 'city' => 'El Baúl'],
            // Delta Amacuro
            ['name' => 'Antonio Díaz', 'city' => 'Curiapo'],
            ['name' => 'Casacoima', 'city' => 'Sierra Imataca'],
            ['name' => 'Pedernales', 'city' => 'Pedernales'],
            ['name' => 'Tucupita', 'city' => 'Tucupita'],
            // Distrito Capital
            ['name' => 'Libertador', 'city' => 'Caracas'],
            // Falcón
            ['name' => 'Acosta', 'city' => 'San Juan de los Cayos'],
            ['name' => 'Bolívar', 'city' => 'San Luis'],
            ['name' => 'Buchivacoa', 'city' => 'Capatárida'],
            ['name' => 'Carirubana', 'city' => 'Punto Fijo'],
            ['name' => 'Colina', 'city' => 'La Vela de Coro'],
            ['name' => 'Dabajuro', 'city' => 'Dabajuro'],
            ['name' => 'Democracia', 'city' => 'Pedregal'],
            ['name' => 'Falcón', 'city' => 'Pueblo Nuevo'],
            ['name' => 'Federación', 'city' => 'Churuguara'],
            ['name' => 'Jacura', 'city' => 'Jacura'],
            ['name' => 'Los Taques', 'city' => 'Santa Cruz de Los Taques'],
            ['name' => 'Mauroa', 'city' => 'Mene de Mauroa'],
            ['name' => 'Miranda', 'city' => 'Coro'],
            ['name' => 'Monseñor Iturriza', 'city' => 'Chichiriviche'],
            ['name' => 'Palmasola', 'city' => 'Palmasola'],
            ['name' => 'Petit', 'city' => 'Cabure'],
            ['name' => 'Píritu', 'city' => 'Píritu'],
            ['name' => 'San Francisco', 'city' => 'Mirimire'],
            ['name' => 'Sucre', 'city' => 'La Cruz de Taratara'],
            ['name' => 'Silva', 'city' => 'Tucacas'],
            ['name' => 'Tocópero', 'city' => 'Tocópero'],
            ['name' => 'Unión', 'city' => 'Santa Cruz de Bucaral'],
            ['name' => 'Urumaco', 'city' => 'Urumaco'],
            ['name' => 'Zamora', 'city' => 'Puerto Cumarebo'],
            // Guárico
            ['name' => 'Camaguán', 'city' => 'Camaguán'],
            ['name' => 'Chaguaramas', 'city' => 'Chaguaramas'],
            ['name' => 'El Socorro', 'city' => 'El Socorro'],
            ['name' => 'Francisco de Miranda', 'city' => 'Calabozo'],
            ['name' => 'José Félix Ribas', 'city' => 'Tucupido'],
            ['name' => 'José Tadeo Monagas', 'city' => 'Altagracia de Orituco'],
            ['name' => 'Juan Germán Roscio', 'city' => 'San Juan de los Morros'],
            ['name' => 'Julián Mellado', 'city' => 'El Sombrero'],
            ['name' => 'Las Mercedes', 'city' => 'Las Mercedes del Llano'],
            ['name' => 'Leonardo Infante', 'city' => 'Valle de la Pascua'],
            ['name' => 'Ortiz', 'city' => 'Ortiz'],
            ['name' => 'Pedro Zaraza', 'city' => 'Zaraza'],
            ['name' => 'San Jerónimo de Guayabal', 'city' => 'Guayabal'],
            ['name' => 'San José de Guaribe', 'city' => 'San José de Guaribe'],
            ['name' => 'Santa María de Ipire', 'city' => 'Santa María de Ipire'],
            ['name' => 'Sebastián Francisco de Miranda', 'city' => 'Palo Seco'],
            // Lara
            ['name' => 'Andrés Eloy Blanco', 'city' => 'Sanare'],
            ['name' => 'Crespo', 'city' => 'Duaca'],
            ['name' => 'Iribarren', 'city' => 'Barquisimeto'],
            ['name' => 'Jiménez', 'city' => 'Quíbor'],
            ['name' => 'Morán', 'city' => 'El Tocuyo'],
            ['name' => 'Palavecino', 'city' => 'Cabudare'],
            ['name' => 'Simón Planas', 'city' => 'Sarare'],
            ['name' => 'Torres', 'city' => 'Carora'],
            ['name' => 'Urdaneta', 'city' => 'Siquisique'],
            // Mérida
            ['name' => 'Alberto Adriani', 'city' => 'El Vigía'],
            ['name' => 'Andrés Bello', 'city' => 'La Azulita'],
            ['name' => 'Antonio Pinto Salinas', 'city' => 'Santa Cruz de Mora'],
            ['name' => 'Aricagua', 'city' => 'Aricagua'],
            ['name' => 'Arzobispo Chacón', 'city' => 'Canaguá'],
            ['name' => 'Campo Elías', 'city' => 'Ejido'],
            ['name' => 'Caracciolo Parra Olmedo', 'city' => 'Tucaní'],
            ['name' => 'Guaraque', 'city' => 'Guaraque'],
            ['name' => 'Justo Briceño', 'city' => 'La Capilla'],
            ['name' => 'Libertador', 'city' => 'Mérida'],
            ['name' => 'Miranda', 'city' => 'Timotes'],
            ['name' => 'Obispo Ramos de Lora', 'city' => 'Santa Elena de Arenales'],
            ['name' => 'Padre Noguera', 'city' => 'Santa María de Caparo'],
            ['name' => 'Pueblo Llano', 'city' => 'Pueblo Llano'],
            ['name' => 'Rangel', 'city' => 'Mucuchíes'],
            ['name' => 'Rivas Dávila', 'city' => 'Bailadores'],
            ['name' => 'Santos Marquina', 'city' => 'Tabay'],
            ['name' => 'Sucre', 'city' => 'Lagunillas'],
            ['name' => 'Tovar', 'city' => 'Tovar'],
            ['name' => 'Tulio Febres Cordero', 'city' => 'Nueva Bolivia'],
            ['name' => 'Zea', 'city' => 'Zea'],
            // Miranda
            ['name' => 'Acevedo', 'city' => 'Caucagua'],
            ['name' => 'Andrés Bello', 'city' => 'San José de Barlovento'],
            ['name' => 'Baruta', 'city' => 'Baruta'],
            ['name' => 'Brión', 'city' => 'Higuerote'],
            ['name' => 'Buroz', 'city' => 'Mamporal'],
            ['name' => 'Carrizal', 'city' => 'Carrizal'],
            ['name' => 'Chacao', 'city' => 'Chacao'],
            ['name' => 'Cristóbal Rojas', 'city' => 'Charallave'],
            ['name' => 'El Hatillo', 'city' => 'El Hatillo'],
            ['name' => 'Guaicaipuro', 'city' => 'Los Teques'],
            ['name' => 'Independencia', 'city' => 'Santa Teresa del Tuy'],
            ['name' => 'Paz Castillo', 'city' => 'Santa Lucía del Tuy'],
            ['name' => 'Pedro Gual', 'city' => 'Cúpira'],
            ['name' => 'Plaza', 'city' => 'Guarenas'],
            ['name' => 'Simón Bolívar', 'city' => 'San Francisco de Yare'],
            ['name' => 'Sucre', 'city' => 'Petare'],
            ['name' => 'Urdaneta', 'city' => 'Cúa'],
            ['name' => 'Zamora', 'city' => 'Guatire'],
            // Monagas
            ['name' => 'Acosta', 'city' => 'San Antonio de Capayacuar'],
            ['name' => 'Aguasay', 'city' => 'Aguasay'],
            ['name' => 'Bolívar', 'city' => 'Caripito'],
            ['name' => 'Caripe', 'city' => 'Caripe'],
            ['name' => 'Cedeño', 'city' => 'Caicara de Maturín'],
            ['name' => 'Ezequiel Zamora', 'city' => 'Punta de Mata'],
            ['name' => 'Libertador', 'city' => 'Temblador'],
            ['name' => 'Piar', 'city' => 'Aragua de Maturín'],
            ['name' => 'Punceres', 'city' => 'Quiriquire'],
            ['name' => 'Santa Bárbara', 'city' => 'Santa Bárbara'],
            ['name' => 'Sotillo', 'city' => 'Barrancas del Orinoco'],
            ['name' => 'Uracoa', 'city' => 'Uracoa'],
            ['name' => 'Maturín', 'city' => 'Maturín'],
            // Nueva Esparta
            ['name' => 'Antolín del Campo', 'city' => 'La Plaza de Paraguachí'],
            ['name' => 'Arismendi', 'city' => 'La Asunción'],
            ['name' => 'Díaz', 'city' => 'San Juan Bautista'],
            ['name' => 'García', 'city' => 'El Valle del Espíritu Santo'],
            ['name' => 'Gómez', 'city' => 'Santa Ana'],
            ['name' => 'Maneiro', 'city' => 'Pampatar'],
            ['name' => 'Marcano', 'city' => 'Juan Griego'],
            ['name' => 'Mariño', 'city' => 'Porlamar'],
            ['name' => 'Península de Macanao', 'city' => 'Boca del Río'],
            ['name' => 'Tubores', 'city' => 'Punta de Piedras'],
            ['name' => 'Villalba', 'city' => 'San Pedro de Coche'],
            // Portuguesa
            ['name' => 'Agua Blanca', 'city' => 'Agua Blanca'],
            ['name' => 'Araure', 'city' => 'Araure'],
            ['name' => 'Esteller', 'city' => 'Píritu'],
            ['name' => 'Guanare', 'city' => 'Guanare'],
            ['name' => 'Guanarito', 'city' => 'Guanarito'],
            ['name' => 'Ospino', 'city' => 'Ospino'],
            ['name' => 'Páez', 'city' => 'Acarigua'],
            ['name' => 'Papelón', 'city' => 'Papelón'],
            ['name' => 'San Genaro de Boconoíto', 'city' => 'San Genaro de Boconoíto'],
            ['name' => 'San Rafael de Onoto', 'city' => 'San Rafael de Onoto'],
            ['name' => 'Santa Rosalía', 'city' => 'El Playón'],
            ['name' => 'Sucre', 'city' => 'Biscucuy'],
            ['name' => 'Turén', 'city' => 'Villa Bruzual'],
            // Sucre
            ['name' => 'Andrés Eloy Blanco', 'city' => 'Casanay'],
            ['name' => 'Andrés Mata', 'city' => 'San José de Aerocuar'],
            ['name' => 'Arismendi', 'city' => 'Río Caribe'],
            ['name' => 'Benítez', 'city' => 'El Pilar'],
            ['name' => 'Bermúdez', 'city' => 'Carúpano'],
            ['name' => 'Bolívar', 'city' => 'Marigüitar'],
            ['name' => 'Cajigal', 'city' => 'Yaguaraparo'],
            ['name' => 'Cruz Salmerón Acosta', 'city' => 'Araya'],
            ['name' => 'Libertador', 'city' => 'Tunapuy'],
            ['name' => 'Mariño', 'city' => 'Irapa'],
            ['name' => 'Mejía', 'city' => 'San Antonio del Golfo'],
            ['name' => 'Montes', 'city' => 'Cumanacoa'],
            ['name' => 'Ribero', 'city' => 'Cariaco'],
            ['name' => 'Sucre', 'city' => 'Cumaná'],
            ['name' => 'Valdéz', 'city' => 'Güiria'],
            // Táchira
            ['name' => 'Andrés Bello', 'city' => 'Cordero'],
            ['name' => 'Antonio Rómulo Costa', 'city' => 'Las Mesas'],
            ['name' => 'Ayacucho', 'city' => 'Colón'],
            ['name' => 'Bolívar', 'city' => 'San Antonio del Táchira'],
            ['name' => 'Cárdenas', 'city' => 'Táriba'],
            ['name' => 'Córdoba', 'city' => 'Santa Ana del Táchira'],
            ['name' => 'Fernández Feo', 'city' => 'San Rafael del Piñal'],
            ['name' => 'Francisco de Miranda', 'city' => 'San José de Bolívar'],
            ['name' => 'García de Hevia', 'city' => 'La Fría'],
            ['name' => 'Guásimos', 'city' => 'Palmira'],
            ['name' => 'Independencia', 'city' => 'Capacho Nuevo'],
            ['name' => 'Jáuregui', 'city' => 'La Grita'],
            ['name' => 'José María Vargas', 'city' => 'El Cobre'],
            ['name' => 'Junín', 'city' => 'Rubio'],
            ['name' => 'Libertad', 'city' => 'Capacho Viejo'],
            ['name' => 'Libertador', 'city' => 'Abejales'],
            ['name' => 'Lobatera', 'city' => 'Lobatera'],
            ['name' => 'Michelena', 'city' => 'Michelena'],
            ['name' => 'Panamericano', 'city' => 'Coloncito'],
            ['name' => 'Pedro María Ureña', 'city' => 'Ureña'],
            ['name' => 'Rafael Urdaneta', 'city' => 'Delicias'],
            ['name' => 'Samuel Darío Maldonado', 'city' => 'La Tendida'],
            ['name' => 'San Cristóbal', 'city' => 'San Cristóbal'],
            ['name' => 'Seboruco', 'city' => 'Seboruco'],
            ['name' => 'Simón Rodríguez', 'city' => 'San Simón'],
            ['name' => 'Sucre', 'city' => 'Queniquea'],
            ['name' => 'Torbes', 'city' => 'San Josecito'],
            ['name' => 'Uribante', 'city' => 'Pregonero'],
            ['name' => 'San Judas Tadeo', 'city' => 'Umuquena'],
            // Trujillo
            ['name' => 'Andrés Bello', 'city' => 'Santa Isabel'],
            ['name' => 'Boconó', 'city' => 'Boconó'],
            ['name' => 'Bolívar', 'city' => 'Sabana Grande'],
            ['name' => 'Candelaria', 'city' => 'Chejendé'],
            ['name' => 'Carache', 'city' => 'Carache'],
            ['name' => 'Escuque', 'city' => 'Escuque'],
            ['name' => 'José Felipe Márquez Cañizalez', 'city' => 'El Paradero'],
            ['name' => 'Juan Vicente Campo Elías', 'city' => 'Campo Elías'],
            ['name' => 'La Ceiba', 'city' => 'Santa Elena de la Ceiba'],
            ['name' => 'Miranda', 'city' => 'El Dividive'],
            ['name' => 'Monte Carmelo', 'city' => 'Monte Carmelo'],
            ['name' => 'Motatán', 'city' => 'Motatán'],
            ['name' => 'Pampán', 'city' => 'Pampán'],
            ['name' => 'Pampanito', 'city' => 'Pampanito'],
            ['name' => 'Rafael Rangel', 'city' => 'Betijoque'],
            ['name' => 'San Rafael de Carvajal', 'city' => 'Carvajal'],
            ['name' => 'Sucre', 'city' => 'Sabana de Mendoza'],
            ['name' => 'Trujillo', 'city' => 'Trujillo'],
            ['name' => 'Urdaneta', 'city' => 'La Quebrada'],
            ['name' => 'Valera', 'city' => 'Valera'],
            // La Guaira
            ['name' => 'Vargas', 'city' => 'La Guaira'],
            // Yaracuy
            ['name' => 'Arístides Bastidas', 'city' => 'San Pablo'],
            ['name' => 'Bolívar', 'city' => 'Aroa'],
            ['name' => 'Cocorote', 'city' => 'Cocorote'],
            ['name' => 'Independencia', 'city' => 'Independencia'],
            ['name' => 'José Antonio Páez', 'city' => 'Sabana de Parra'],
            ['name' => 'La Trinidad', 'city' => 'Boraure'],
            ['name' => 'Manuel Monge', 'city' => 'Yumare'],
            ['name' => 'Nirgua', 'city' => 'Nirgua'],
            ['name' => 'San Felipe', 'city' => 'San Felipe'],
            ['name' => 'Sucre', 'city' => 'Guama'],
            ['name' => 'Urachiche', 'city' => 'Urachiche'],
            ['name' => 'Veroes', 'city' => 'Farriar'],
            ['name' => 'Peña', 'city' => 'Yaritagua'],
            // Zulia
            ['name' => 'Almirante Padilla', 'city' => 'El Toro'],
            ['name' => 'Baralt', 'city' => 'San Timoteo'],
            ['name' => 'Cabimas', 'city' => 'Cabimas'],
            ['name' => 'Catatumbo', 'city' => 'Encontrados'],
            ['name' => 'Colón', 'city' => 'San Carlos del Zulia'],
            ['name' => 'Francisco Javier Pulgar', 'city' => 'Pueblo Nuevo'],
            ['name' => 'La Guajira', 'city' => 'Sinamaica'],
            ['name' => 'Jesús Enrique Lossada', 'city' => 'La Concepción'],
            ['name' => 'Jesús María Semprún', 'city' => 'Casigua El Cubo'],
            ['name' => 'La Cañada de Urdaneta', 'city' => 'La Concepción'],
            ['name' => 'Lagunillas', 'city' => 'Ciudad Ojeda'],
            ['name' => 'Machiques de Perijá', 'city' => 'Machiques'],
            ['name' => 'Mara', 'city' => 'San Rafael del Moján'],
            ['name' => 'Maracaibo', 'city' => 'Maracaibo'],
            ['name' => 'Miranda', 'city' => 'Los Puertos de Altagracia'],
            ['name' => 'Rosario de Perijá', 'city' => 'La Villa del Rosario'],
            ['name' => 'San Francisco', 'city' => 'San Francisco'],
            ['name' => 'Santa Rita', 'city' => 'Santa Rita'],
            ['name' => 'Simón Bolívar', 'city' => 'Tía Juana'],
            ['name' => 'Sucre', 'city' => 'Bobures'],
            ['name' => 'Valmore Rodríguez', 'city' => 'Valmore Rodríguez'],
            ['name' => 'José María Semprún', 'city' => 'Casigua el Cubo'],
        ];

        // Insertar los municipios en la base de datos
        foreach ($allMunicipalities as $municipality) {
            $city = $cities[$municipality['city']] ?? null;

            if ($city) {
                DB::table('municipalities')->insert([
                    'name' => $municipality['name'],
                    'city_id' => $city->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}